### ISSUE TITLE
Custom card feature not working

### ISSUE THREAD

**Issue by taucher4000** [puterboy/HAOS-kiosk#7]
First of all I want to say thank you for this awesome add-on. This is actually what I was looking for to make my RV smart. I have a Raspberry Pi with a 5 inch display directly connected to the Pi where the Home Assistant is running on. With your add-on, I'm now able to use the same Hardware as the server and display at the same time.

For the dashboard, I'm using the "Custom card feature" which HA just announced (https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card-feature/). I'm using [this](https://github.com/Nerwyn/custom-card-features) HACS extension. The extension is working fine and and I'm able to create custom components like toggle or sliders (see screenshot). Unfortunately, all the custom card components are not controllable in HAOS-Kiosk (but working fine on the Desktop computer). They are visible but not clickable. All other standard card elements in the dashboard are working just fine. Only the custom card features are not working. 

My assumption is that something is either wrong with luakit or a configuration is missing.

![Image](https://github.com/user-attachments/assets/35f0c3b1-43db-406b-a682-ddb626af94e7)

The card is created like the following:

```
features:
  - type: custom:service-call
    entries:
      - type: spinbox
        entity_id: input_number.test
        range:
          - 0
          - 100
        tap_action:
          action: perform-action
          target:
            entity_id: input_number.test
          perform_action: counter.increment
          data: {}
        step: 1
        label: "{{value}}"
type: tile
entity: input_number.test
features_position: inline
vertical: false
```
